BEGIN TRAN Tr1
UPDATE BookInLib SET StatusID=StatusID+2
WHERE LibID = 1;
SELECT * FROM BookInLib;
SAVE TRAN SaveP1;
INSERT INTO BookInLib VALUES (5,2,2);
ROLLBACK TRAN SaveP1;
SELECT * FROM BookInLib;
